### ISSUE TITLE
cant connect on non standard mysql port

### ISSUE THREAD

**Issue by Freundschaft** [audacioustux/mautic-chart#4]
Im receiving the following log:
```

│ Creating database mautic, if it does not already exist...                                                                                                                                                                                 │
│ ERROR 2002 (HY000): Can't connect to server on 'xx.xx.xx.xx' (115)                                                                                                                                                                      │
│ stream closed EOF for default/mautic-install-1734101951-pkxxj (mautic)      
```

my config looks like this:
```

ingress:
  enabled: false
mautic:
  configMap:
    MAUTIC_SAML_IDP_ENTITY_ID: "https://mautic.xxx.org"
    MAUTIC_APP_DEBUG: "1"
  db:
    create: true
    configMap:
      MAUTIC_DB_HOST: "xx.xx.xx.xx"
      MAUTIC_DB_PORT: "20415"
      MAUTIC_DB_NAME: mautic
    secret:
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mautic
  persistence:
    accessMode: ReadWriteOnce
```

is it possible that the port setting is not applied? any advice on how to debug?

Thanks & Best

**Comment by audacioustux** [comment]
you may exec into the mautic container, and check the config file and see if the ports are properly set there... https://github.com/audacioustux/mautic-chart/blob/main/bin/sync_config.php this might be relevant for you to debug

**Comment by Freundschaft** [comment]
maybe its because php expects an integer value for the port, but in the environment variable its only possible to pass it as a string?

**Comment by audacioustux** [comment]
hummm... could be.. but environment variables are by nature strings... not sure what'd be the best approach to resolve this. have to look into it later maybe, or you may submit a PR

**Comment by Freundschaft** [comment]
hmhm no thats not the issue, i just tried by exec'ing into the container, looks like the port is correctly written, ill do some more research

its also strange cause i can connect from within the pod to the server by using the mysql command, but the setup command fails immediately when configured with the server

**Comment by Freundschaft** [comment]
ok no idea what was wrong, i just found another solution by moving to another mysql server now everything works 🤷
